config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  get 'members', to: 'club#index', as: 'members'

  devise_for :users, controllers: {registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/club_controller.rb
class ClubController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/club/index.html.erb
<div class="center jumbotron">
  <h1>Liste des membres</h1>
</div>



<div class="shadow mt-5 p-5 col-lg-10 offset-lg-1 bg-light">
  <table class="table table-striped table-dark">
    <thead>
      <tr class="bg-primary">
        <th scope="col">Nom</th>
        <th scope="col">Prénoms</th>
        <th scope="col">Email</th>
        <th scope="col">Date d'inscription</th>
      </tr>
    </thead>
    <tbody>

      <%=%>
    
      <% @users.each do |u| %>
      <tr>
        <th scope="row"><%= u.first_name%></th>
        <td><%= u.last_name %></td>
        <td><%= u.email %></td>
        <td><%= Date.parse(u.created_at.to_s).strftime('%a %d %b %Y') %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<div class="container" style="margin-top: 100px">
<% if user_signed_in? %>
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Bonjour <%= current_user.last_name%>!</h4>
  <p>Vous pouvez accèder à la liste des membres dans <a href="<%= members_path %>">ici</a></p>
</div>
<% else %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">Désolé!</h4>
  <p>Veuillez vous logger/inscrire si vous voulez voir la liste des membres du club.</p>
  <hr>
  <p class="mb-0">
    <a class="btn btn-primary" href="<%= new_user_session_path %>">Se logger</a>
    <a class="btn btn-success" href="<%= new_user_registration_path %>">S'inscrire</a>
  </p>
</div>
<% end %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark shadow" style="background-color: #373634">
  <a class="navbar-brand" href="<%= root_path%>">Club moussaillon ⛵😇 </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">Accueil</a>
      </li>
    </ul>
    <form class="form-inline">
      <%if user_signed_in? %>
      <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger my-2 my-sm-0' %>
      <%else%>
      <a href="<%= new_user_session_path %>" class="btn btn-outline-success my-2 my-sm-0">Se connecter ou s'inscrire?</a>
      <%end%>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Club mousaillon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>
  </body>
  <script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
</html>